### PR TITLE
Add scalajs-env-jsdom-nodejs

### PR DESCRIPTION
**Pull request by lolgab**
Now all the tests pass except one.
The "proper escaping" test fails because a wrong substitution in `TestUtil.clean`.
Didn't spend time to debug it, by the way.

### CODE REVIEW

**Comment by lihaoyi** [comment]
@lolgab I'm seeing the following failure in travis

```
[80/314] scalatags.js[2.12.10,0.6.32].test.test 
Starting process: node
/home/travis/build/lihaoyi/scalatags/node_modules/webidl-conversions/lib/index.js:357
    } catch {
            ^
SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/travis/build/lihaoyi/scalatags/node_modules/jsdom/lib/jsdom/browser/Window.js:3:27)
1 targets failed
scalatags.js[2.12.10,0.6.32].test.test org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: Node.js with JSDOM exited with code 1
The command "./mill scalatags.js.__.test.test" exited with 1.
```

**Comment by lolgab** [comment]
@lihaoyi
Correct. Debugging it.

**Comment by lolgab** [comment]
@lihaoyi Ready for another review round.

**Comment by lihaoyi** [comment]
@lolgab how about we just disable `scalatags.jsdom.ExampleTests.properEscaping` for the JS/JSDOM backend tests? If we're going to make more tests work, might as well go for green

**Comment by lolgab** [comment]
The test itself is correct, it is the code that removes the extra spaces and newlines that is broken. If you don't mind I can skip that and have a long single-line string in that test case.

**Comment by lolgab** [comment]
Done ✅

**Comment by lolgab** [comment]
✅ Green Travis 🎉

**Comment by lihaoyi** [comment]
shipit

**Pull request merged**
