### PR TITLE
Add support for Scala Native 0.3 and 0.4.0-M2

### PR DESCRIPTION
**Pull request by lolgab**

### CODE REVIEW

**Comment by lihaoyi** [comment]
@lolgab let me know when this is ready and I'll publish it

**Comment by lolgab** [comment]
@lihaoyi Sure! In the meantime you can check pprint which is green on CI.

**Comment by lolgab** [comment]
I think here there is a problem with mill..
it can't find `phantomjs` in the Scala.js 1.0.0 build

**Comment by lihaoyi** [comment]
@lolgab haha yeah the scala.js 1.0.0 build is borked. Feel free to ignore it if the others work. I haven't figured out how to get the scala.js phantomjs support working; @sjrd told me once but I forgot and I can't find what he said in the gitter history...

**Comment by lolgab** [comment]
Then I think the Scala Native part is ok :D

**Comment by sjrd** [comment]
Just stop using PhantomJS. Use the jsdom environment instead.

We do support PhantomJS in 1.0.0 through https://github.com/scala-js/scala-js-env-phantomjs, but PhantomJS itself has been *officially* dead for years: https://phantomjs.org/

**Comment by lihaoyi** [comment]
@sjrd haha yes I know it's been dead, but I'm too lazy to fix my test suite :P I'll try the `scala-js-env-phantomjs! thing you linked

**Comment by lihaoyi** [comment]
@lolgab 

```
[107/107] mill.scalalib.PublishModule.publishAll
Uploading com/lihaoyi/scalatags_native0.3_2.11/0.8.6/scalatags_native0.3_2.11-0.8.6.jar
Uploading com/lihaoyi/scalatags_native0.3_2.11/0.8.6/scalatags_native0.3_2.11-0.8.6.jar.md5
Uploading com/lihaoyi/scalatags_native0.3_2.11/0.8.6/scalatags_native0.3_2.11-0.8.6.jar.sha1
Uploading com/lihaoyi/scalatags_native0.3_2.11/0.8.6/scalatags_native0.3_2.11-0.8.6-sources.jar
Uploading com/lihaoyi/scalatags_native0.3_2.11/0.8.6/scalatags_native0.3_2.11-0.8.6-sources.jar.md5
Uploading com/lihaoyi/scalatags_native0.3_2.11/0.8.6/scalatags_native0.3_2.11-0.8.6-sources.jar.sha1
Uploading com/lihaoyi/scalatags_native0.3_2.11/0.8.6/scalatags_native0.3_2.11-0.8.6-javadoc.jar
Uploading com/lihaoyi/scalatags_native0.3_2.11/0.8.6/scalatags_native0.3_2.11-0.8.6-javadoc.jar.md5
Uploading com/lihaoyi/scalatags_native0.3_2.11/0.8.6/scalatags_native0.3_2.11-0.8.6-javadoc.jar.sha1
Uploading com/lihaoyi/scalatags_native0.3_2.11/0.8.6/scalatags_native0.3_2.11-0.8.6.pom
Uploading com/lihaoyi/scalatags_native0.3_2.11/0.8.6/scalatags_native0.3_2.11-0.8.6.pom.md5
Uploading com/lihaoyi/scalatags_native0.3_2.11/0.8.6/scalatags_native0.3_2.11-0.8.6.pom.sha1
Uploading com/lihaoyi/scalatags_native0.3_2.11/0.8.6/scalatags_native0.3_2.11-0.8.6.jar.asc
Uploading com/lihaoyi/scalatags_native0.3_2.11/0.8.6/scalatags_native0.3_2.11-0.8.6.jar.asc.md5
Uploading com/lihaoyi/scalatags_native0.3_2.11/0.8.6/scalatags_native0.3_2.11-0.8.6.jar.asc.sha1
Uploading com/lihaoyi/scalatags_native0.3_2.11/0.8.6/scalatags_native0.3_2.11-0.8.6-sources.jar.asc
Uploading com/lihaoyi/scalatags_native0.3_2.11/0.8.6/scalatags_native0.3_2.11-0.8.6-sources.jar.asc.md5
Uploading com/lihaoyi/scalatags_native0.3_2.11/0.8.6/scalatags_native0.3_2.11-0.8.6-sources.jar.asc.sha1
Uploading com/lihaoyi/scalatags_native0.3_2.11/0.8.6/scalatags_native0.3_2.11-0.8.6-javadoc.jar.asc
Uploading com/lihaoyi/scalatags_native0.3_2.11/0.8.6/scalatags_native0.3_2.11-0.8.6-javadoc.jar.asc.md5
Uploading com/lihaoyi/scalatags_native0.3_2.11/0.8.6/scalatags_native0.3_2.11-0.8.6-javadoc.jar.asc.sha1
Uploading com/lihaoyi/scalatags_native0.3_2.11/0.8.6/scalatags_native0.3_2.11-0.8.6.pom.asc
Uploading com/lihaoyi/scalatags_native0.3_2.11/0.8.6/scalatags_native0.3_2.11-0.8.6.pom.asc.md5
Uploading com/lihaoyi/scalatags_native0.3_2.11/0.8.6/scalatags_native0.3_2.11-0.8.6.pom.asc.sha1
Uploading com/lihaoyi/scalatags_native0.4.0-M2_2.11/0.8.6/scalatags_native0.4.0-M2_2.11-0.8.6.jar
Uploading com/lihaoyi/scalatags_native0.4.0-M2_2.11/0.8.6/scalatags_native0.4.0-M2_2.11-0.8.6.jar.md5
Uploading com/lihaoyi/scalatags_native0.4.0-M2_2.11/0.8.6/scalatags_native0.4.0-M2_2.11-0.8.6.jar.sha1
Uploading com/lihaoyi/scalatags_native0.4.0-M2_2.11/0.8.6/scalatags_native0.4.0-M2_2.11-0.8.6-sources.jar
Uploading com/lihaoyi/scalatags_native0.4.0-M2_2.11/0.8.6/scalatags_native0.4.0-M2_2.11-0.8.6-sources.jar.md5
Uploading com/lihaoyi/scalatags_native0.4.0-M2_2.11/0.8.6/scalatags_native0.4.0-M2_2.11-0.8.6-sources.jar.sha1
Uploading com/lihaoyi/scalatags_native0.4.0-M2_2.11/0.8.6/scalatags_native0.4.0-M2_2.11-0.8.6-javadoc.jar
Uploading com/lihaoyi/scalatags_native0.4.0-M2_2.11/0.8.6/scalatags_native0.4.0-M2_2.11-0.8.6-javadoc.jar.md5
Uploading com/lihaoyi/scalatags_native0.4.0-M2_2.11/0.8.6/scalatags_native0.4.0-M2_2.11-0.8.6-javadoc.jar.sha1
Uploading com/lihaoyi/scalatags_native0.4.0-M2_2.11/0.8.6/scalatags_native0.4.0-M2_2.11-0.8.6.pom
Uploading com/lihaoyi/scalatags_native0.4.0-M2_2.11/0.8.6/scalatags_native0.4.0-M2_2.11-0.8.6.pom.md5
Uploading com/lihaoyi/scalatags_native0.4.0-M2_2.11/0.8.6/scalatags_native0.4.0-M2_2.11-0.8.6.pom.sha1
Uploading com/lihaoyi/scalatags_native0.4.0-M2_2.11/0.8.6/scalatags_native0.4.0-M2_2.11-0.8.6.jar.asc
Uploading com/lihaoyi/scalatags_native0.4.0-M2_2.11/0.8.6/scalatags_native0.4.0-M2_2.11-0.8.6.jar.asc.md5
Uploading com/lihaoyi/scalatags_native0.4.0-M2_2.11/0.8.6/scalatags_native0.4.0-M2_2.11-0.8.6.jar.asc.sha1
Uploading com/lihaoyi/scalatags_native0.4.0-M2_2.11/0.8.6/scalatags_native0.4.0-M2_2.11-0.8.6-sources.jar.asc
Uploading com/lihaoyi/scalatags_native0.4.0-M2_2.11/0.8.6/scalatags_native0.4.0-M2_2.11-0.8.6-sources.jar.asc.md5
Uploading com/lihaoyi/scalatags_native0.4.0-M2_2.11/0.8.6/scalatags_native0.4.0-M2_2.11-0.8.6-sources.jar.asc.sha1
Uploading com/lihaoyi/scalatags_native0.4.0-M2_2.11/0.8.6/scalatags_native0.4.0-M2_2.11-0.8.6-javadoc.jar.asc
Uploading com/lihaoyi/scalatags_native0.4.0-M2_2.11/0.8.6/scalatags_native0.4.0-M2_2.11-0.8.6-javadoc.jar.asc.md5
Uploading com/lihaoyi/scalatags_native0.4.0-M2_2.11/0.8.6/scalatags_native0.4.0-M2_2.11-0.8.6-javadoc.jar.asc.sha1
Uploading com/lihaoyi/scalatags_native0.4.0-M2_2.11/0.8.6/scalatags_native0.4.0-M2_2.11-0.8.6.pom.asc
Uploading com/lihaoyi/scalatags_native0.4.0-M2_2.11/0.8.6/scalatags_native0.4.0-M2_2.11-0.8.6.pom.asc.md5
Uploading com/lihaoyi/scalatags_native0.4.0-M2_2.11/0.8.6/scalatags_native0.4.0-M2_2.11-0.8.6.pom.asc.sha1
Published scalatags_native0.3_2.11, scalatags_native0.4.0-M2_2.11 to Sonatype
Closing staging repository
Waiting for staging repository to close
Promoting staging repository
Waiting for staging repository to release
Dropping staging repository
Published scalatags_native0.3_2.11, scalatags_native0.4.0-M2_2.11 successfully

**Pull request merged**
