### PR TITLE
support Scala 2.13.0-M5 (and drop Scala 2.10 and JDK 7 support)

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
added another commit bumping Scala to 2.12.8. can this be merged?

**Comment by aeons** [comment]
This is one of the dependencies blocking http4s to support 2.13.0-M5.

Would love for this to get merged.

**Comment by lihaoyi** [comment]
I can't publish this myself, due to SBT blowing up on some java 11 scala 2.10 incompatibility. If someone else wants it published maybe @alexarchambault or @olafurpg can help? Or send a PR to get it working on Java 11 and I'll try again

**Comment by SethTisue** [comment]
@lihaoyi scalatags is green on JDK 11 at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4126/ , and I was able to run `publishLocal` on JDK 11

how can I, or any of us, reproduce the problem you hit, so we can try to help? obviously I can't do a full `publish` ("refused by the server: Unauthorized", and rightly so)

**Comment by SethTisue** [comment]
this is now blocking http4s over at https://github.com/http4s/http4s/pull/2393 , @lihaoyi could you take a second look at this?

**Comment by lihaoyi** [comment]
@SethTisue I can send you publishing creds if it works on your machine

**Comment by SethTisue** [comment]
@lihaoyi I can't get involved with that, there are almost 200 projects in the community build, but perhaps someone else who watches this repo would like to volunteer?

**Comment by lihaoyi** [comment]
Perhaps the http4s guys could help if it's blocking them? Or @alexarchambault since you're already re-publishing a bunch of my libraries for 2.13-M5?

My personal policy is that I'll keep things up to date on major releases, but I can't commit to chasing the bleeding edge of milestones and release candidates, but if anyone wants to help chase them on my behalf I'll gladly farm out my creds

**Comment by alexarchambault** [comment]
`0.6.8` is on its way to Central (already on [Sonatype public](https://oss.sonatype.org/content/repositories/public/com/lihaoyi/scalatags_2.13.0-M5/)).

**Pull request merged**
