### PR TITLE
- Adds a shorthand for empty attributes called emptyAttr

### PR DESCRIPTION
**Pull request by mdedetrich**
Sort of related to https://github.com/lihaoyi/scalatags/issues/33, added an method on strings called `emptyAttr`, which is basically a shorthand of

```scala
"someAttr".attr:="someAttr"
```

You would now do
```scala
"someAttr".emptyAttr
```

Looks cleaner, and it makes a big difference when using frameworks like `AngularJS`, that use a lot of defined (and large) empty attributes

Test's haven't been added since the definition is so trivial, but I can easily add one if needed

### CODE REVIEW

**Comment by lihaoyi** [comment]
I don't really think this is worth it, given how small a benefit this is:

- For all the in-built attributes, this will not benefit you at all since they're already defined as such
- For your own attributes, you probably won't be defining very many
- If you are defining lots, you can write your own helper

Overall it could live in lihaoyi/scalatags or it could live in your own project and be equally usable, and I feel for now it lacks the demand to go into lihaoyi/scalatags

**Comment by mdedetrich** [comment]
Just to give a personal usecase, there are already around >100 instances in our codebase doing something which is abstracted by `.emptyAttr`

> For all the in-built attributes, this will not benefit you at all since they're already defined as such
Agreed, however ScalaTags does seem to miss quite a few attributes (even the ones in html). While it can be argued that pull requests should be done to fill them in, there are edge cases (such as emails, or even custom libraries such as angular where you define your own html attributes, which we can't cover)

> For your own attributes, you probably won't be defining very many
As said above, this is quite false in our case, we have to define a lot. A lot of the major client side javascript frameworks that deal with the concept of web components, you define (or use) a huge number of custom attributes. While it can be argued that "this isn't idiomatic scala web side dev", the impression I get from ScalaTags is its just a HTML tempting library, it shouldn't be making assumptions

> If you are defining lots, you can write your own helper

Which is what we have done for now, however I am now using this same helper in other projects as well. If you see the same helper definition in a lot of projects, ods are it probably should be in the actual library

Final point is, and I think this is a fairly compelling reason, is that `.emptyAttr` provides an actual definition of what an empty attribute is. For example, with XHTML, you can't have completely empty tags, and it so happens that `ng-databind="ng-databind"` is the same as `ng-databind`. Some people don't know this, but the `.emptyAttr` makes this crystal clear.

**Comment by lihaoyi** [comment]
Re-opening because apparently this is part of the spec

https://www.w3.org/TR/html-markup/syntax.html#syntax-attr-empty
http://stackoverflow.com/questions/21643365/empty-attribute

so perhaps it should go in

**Comment by lihaoyi** [comment]
After discussion, I am convinced.

Could you do a few things before landing:

- Rebase on master
- Add a line to the 0.5.5 changelog
- Add something about this into the readme (I'm not sure where, you'll have to find a spot)
- Update the remaining empty attributes in the codebase to use `emptyAttr`. There are more that you didn't hit:

```
haoyi-mbp:scalatags haoyi$ find scalatags/shared/src/main -name "*.scala" | xargs grep "attr :="
scalatags/shared/src/main/scala/scalatags/generic/Attrs.scala:  lazy val draggable	= "draggable".attr := "draggable"
scalatags/shared/src/main/scala/scalatags/generic/Attrs.scala:  lazy val hidden = "hidden".attr := "hidden"
scalatags/shared/src/main/scala/scalatags/generic/Attrs.scala:  lazy val spellcheck = "spellcheck".attr := "spellcheck"
scalatags/shared/src/main/scala/scalatags/generic/Attrs.scala:  lazy val translate	= "translate".attr := "translate"
scalatags/shared/src/main/scala/scalatags/generic/Attrs.scala:  lazy val selected = "selected".attr := "selected"
scalatags/shared/src/main/scala/scalatags/generic/Attrs.scala:  lazy val autofocus = "autofocus".attr := "autofocus"
scalatags/shared/src/main/scala/scalatags/generic/Attrs.scala:  lazy val checked = "checked".attr := "checked"
scalatags/shared/src/main/scala/scalatags/generic/Attrs.scala:  lazy val multiple = "multiple".attr := "multiple"
scalatags/shared/src/main/scala/scalatags/generic/Attrs.scala:  lazy val readonly = "readonly".attr := "readonly"
scalatags/shared/src/main/scala/scalatags/generic/Attrs.scala:  lazy val required = "required".attr := "required"
scalatags/shared/src/main/scala/scalatags/generic/Attrs.scala:  lazy val disabled = "disabled".attr := "disabled"
```

After that, I'll merge it. Thanks for pushing this through!

**Comment by mdedetrich** [comment]
Benchmarks for `@inline` on `.emptyAttr` are https://gist.github.com/mdedetrich/3aa488c7a3bcaca960de

**Comment by lihaoyi** [comment]
This looks good. I'll take another look at perf later, but that's irrelevant to the issue of `emptyAttr`

**Pull request merged**
