### PR TITLE
allow building on JDK 11

### PR DESCRIPTION
**Pull request by SethTisue**
this is desirable for the Scala community build.  but also
desirable in general

### CODE REVIEW

**Comment by SethTisue** [comment]
ready for review/merge

**Comment by SethTisue** [comment]
any maintainers around...?

**Comment by SethTisue** [comment]
@lihaoyi I think I remember seeing a previous tweet of yours, a while back, that said scalatags was seeking new maintainers. shall we try to tweet again about it...? I could help with the publicity, not just on Twitter, but elsewhere too.

**Comment by lihaoyi** [comment]
Yeah would be nice to have more people help maintaining this stuff, but I can merge this for now

**Comment by SethTisue** [comment]
thanks 👍

**Pull request merged**
